CREATE DATABASE RH 

USE RH

CREATE TABLE FUNCIONARIOS(
ID_FUNC INTEGER IDENTITY(1,1) NOT NULL CONSTRAINT PK_ID_FUNCIONARIO PRIMARY KEY (ID_FUNC), 
NOME VARCHAR(50) NOT NULL, 
ENDERECO VARCHAR(50),
ADMISSAO DATETIME NOT NULL, 
SALARIO DECIMAL(14,2) NOT NULL,
CARGO VARCHAR(20) NOT NULL
);

