IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'RH')
BEGIN
    CREATE DATABASE RH
END
GO

USE RH
GO

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='CARGOS' and xtype='U')
BEGIN
    CREATE TABLE CARGOS (
        ID_CARGO INTEGER IDENTITY(1,1) NOT NULL CONSTRAINT PK_ID_CARGO PRIMARY KEY (ID_CARGO), 
        CAR_NOME VARCHAR(20) NOT NULL
    );
END

IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='FUNCIONARIOS' and xtype='U')
BEGIN
    CREATE TABLE FUNCIONARIOS (
        ID_FUNC INTEGER IDENTITY(1,1) NOT NULL CONSTRAINT PK_ID_FUNCIONARIO PRIMARY KEY (ID_FUNC), 
        NOME VARCHAR(50) NOT NULL, 
        ENDERECO VARCHAR(50),
        ADMISSAO DATETIME NOT NULL, 
        SALARIO DECIMAL(14,2) NOT NULL,
        CARGO INT CONSTRAINT FK_ID_CARGO FOREIGN KEY (CARGO) REFERENCES CARGOS (ID_CARGO)
    );
END
